language: node_js

node_js:
  - '10'

addons:
  chrome: stable
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify

notifications:
  slack:
    rooms:
    - ibm-casdesign:P44xeoRDixDw38uE025Qoekz
    on_pull_requests: false
    on_success: change
    on_failure: always
    template:
    - "`%{repository_name}` *%{result}* build <%{build_url}|#%{build_number}>"
    - "Commit #<%{compare_url}|%{commit}> %{commit_message}"
    - "Author: *%{author}*"
    - "Execution time: *%{duration}*"
    - "Message: %{message}"
  email: false

branches:
  only:
    - master

script: skip

stages:
  - "deploy"

install:
  - sed -i "s#ssh://git@github.ibm.com:#https://$GITHUB_TOKEN@github.ibm.com/#g" package.json
  - npm install

jobs:
  fast_finish: true
  include:
  - stage: "deploy"
    # before_script:
    # - yarn build
    script:
    - npm run build
    # - npm run cy:ci
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
      github_url: github.ibm.com
      local_dir: public
      on:
        branch: master