name: Deploy website to GHE Github Pages

on:
  push:
    branches:
      - chore/fix-build

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn
      - name: Gatsby Cache Folder
        uses: actions/cache@v3
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby
      - name: Gatsby Public Folder
        uses: actions/cache@v3
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby
      - name: Build project
        run: yarn build
      - name: Deploy build artifacts to gh-pages
        run: |
          git config --global user.name ${{ secrets.BOT_NAME }}
          git config --global user.email ${{ secrets.BOT_EMAIL}}

          git remote add ghe-pal https://${{ secrets.BOT_NAME }}:${{ secrets.GHE_CARBON_PERSONAL_ACCCESS_TOKEN }}@github.ibm.com/CDAI-design/pal.git
          git fetch ghe-pal public-deploy-workflow-test
          git checkout -b public-deploy-workflow-test ghe-pal/public-deploy-workflow-test
          git update-ref -d refs/remotes/ghe-pal/public-deploy-workflow-test
          git pull ghe-pal public-deploy-workflow-test

          echo 'test push from public/internal repo pt 2' > test.txt
          git add .
          git commit -m 'chore(test): test deploy from GH public/internal repo'
          git push ghe-pal public-deploy-workflow-test
